name: CfRR
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter-book
  - jupyter-cache
  - nbclient
  - nbconvert
  - nbformat
  - sphinx
  - sphinx-book-theme
  - sphinx-comments
  - sphinx-copybutton
  - sphinx-design
  - sphinx-external-toc
  - sphinx-jupyterbook-latex
  - sphinx-multitoc-numbering
  - sphinx-thebe
  - sphinx-togglebutton
  - sphinxcontrib-applehelp
  - sphinxcontrib-bibtex
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - notebook-shim
  - widgetsnbextension
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - plotly
  - bokeh
  - hvplot
  - holoviews
  - panel
  - xarray
  - numba
  - dask
  - fpdf
  - ghp-import
  - jsonpickle
  - jupyterquiz
  - notebook
  - pyspellchecker
  - pyvis
  - pyviz
  - rpy2
  - tzlocal
  - pip
  - pip:
    - notebook==7.2.0
