name: CfRR
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter-book
  - ipykernel
  - ipython
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - plotly
  - ghp-import
  - notebook
  - rpy2
  - pip:
    - jupyterquiz==2.6.3
    - notebook==7.2.0
    - pyviz==0.9
