# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Coding For Reproducible Research
author: Coding For Reproducible Research Community
logo: images/exeter_logo.png
copyright: "2024"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/berrli/CfRR_Courses  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_issues_button: true

launch_buttons:
  thebe                  : true


# Files not to be ran when building the jupyter book
exclude_patterns:
  - run_scripts_for_data.ipynb
  - README.md
  - course_details_markdowns/advanced_regression_analysis.md
  - course_details_markdowns/all_upcoming_workshops.md
  - course_details_markdowns/computational_thinking.md
  - course_details_markdowns/intermediate_python.md
  - course_details_markdowns/intermediate_version_control.md
  - course_details_markdowns/introduction_to_hpc_at_exeter.md
  - course_details_markdowns/introduction_to_julia.md
  - course_details_markdowns/introduction_to_machine_learning.md
  - course_details_markdowns/introduction_to_python.md
  - course_details_markdowns/introduction_to_r.md
  - course_details_markdowns/introduction_to_unix.md
  - course_details_markdowns/introduction_to_version_control.md
  - course_details_markdowns/parallel_computing.md
  - course_details_markdowns/regression_analysis_with_r.md
  - data/admin/workshop_details.md
  - course_details_markdowns/introduction_to_version_control_with_git_and_github.md
  - course_details_markdowns/software_development_best_practice.md
  - course_details_markdowns/upcoming_workshops.md
  - course_details_markdowns/working_with_data_in_r.md
  - pathways/descriptions/data_scientist.md
  - pathways/descriptions/software_engineer.md

