name: Build Book

# Run this on pull requests
on:
  pull_request:
    branches:
      - main

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # (optional) Cache your executed notebooks between runs
    - name: Cache executed notebooks
      uses: actions/cache@v3
      with:
        path: _build/.jupyter_cache
        key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Always upload logs, even if build succeeds
    - name: Upload error logs
      uses: actions/upload-artifact@v3
      with:
        name: error-logs
        path: _build/html/reports/pathways/related_courses.err.log
      continue-on-error: true
